# Generated by Django 4.0.7 on 2024-01-15 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='contnet',
            new_name='content',
        ),
    ]
