# Generated by Django 4.0.7 on 2024-01-17 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='subscriber_count',
            new_name='followers_count',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='subscription_count',
            new_name='followings_count',
        ),
    ]
